import { Router } from 'express';
import { chat, getKnowledge, addKnowledge, updateKnowledge, deleteKnowledge } from '../controllers/chatbotController';
import { authenticate, requireAdmin } from '../middleware/auth';
const router = Router();
router.post('/chat', chat);
router.get('/knowledge', authenticate, requireAdmin, getKnowledge);
router.post('/knowledge', authenticate, requireAdmin, addKnowledge);
router.put('/knowledge/:id', authenticate, requireAdmin, updateKnowledge);
router.delete('/knowledge/:id', authenticate, requireAdmin, deleteKnowledge);
export default router;
